name: App Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12.1]

    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ../requirements.txt
      - name: Test App Code
        run: python ./test_app.py