name: App Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/

    strategy:
      matrix:
        python-version: [3.8]

    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: kishaningithub/setup-python-amazon-linux@v1
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

      - name: Test App
        run: |
            pytest test_app.py