# .github/workflows/test.yml

name: Test

on:
  push:
    branches:
      - test-api-auto

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: backend  # Specify the branch name where test_news.py is located

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests/test_backend.py
        env:
          NEWS_API_KEY_TEST: ${{ secrets.NEWS_API_KEY_TEST }}
